# Generated by Django 3.0.3 on 2020-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopstop", "0003_listitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="listitem",
            name="bought",
            field=models.BooleanField(
                default=False, verbose_name="Item has been bought"
            ),
        ),
    ]
