# Generated by Django 3.0.3 on 2020-02-20 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopstop", "0004_listitem_bought"),
    ]

    operations = [
        migrations.AddField(
            model_name="listitem",
            name="time_added",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
